/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    products: Product;
    simulations: Simulation;
    'customer-agents': CustomerAgent;
    conversations: Conversation;
    messages: Message;
    reports: Report;
    'custom-simulation-requests': CustomSimulationRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    simulations: SimulationsSelect<false> | SimulationsSelect<true>;
    'customer-agents': CustomerAgentsSelect<false> | CustomerAgentsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    'custom-simulation-requests': CustomSimulationRequestsSelect<false> | CustomSimulationRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'analyst' | 'business-owner' | 'viewer';
  company?: string | null;
  avatar?: (number | null) | Media;
  isActive?: boolean | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Local uploads are for development only. Production storage is configured later.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  category: 'avatar' | 'product' | 'page' | 'report' | 'general';
  uploadedBy: number | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe identifier generated from the title or name when left empty.
   */
  slug: string;
  status: 'draft' | 'published' | 'archived';
  metaTitle?: string | null;
  metaDescription?: string | null;
  hero?: HeroBlock[] | null;
  contentBlocks?: (ContentBlock | FeatureGridBlock)[] | null;
  publishedAt?: string | null;
  author: number | User;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  description?: string | null;
  image?: (number | null) | Media;
  primaryAction?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock".
 */
export interface FeatureGridBlock {
  heading?: string | null;
  features?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'feature-grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  owner: number | User;
  name: string;
  /**
   * URL-safe identifier generated from the title or name when left empty.
   */
  slug: string;
  category: string;
  description: string;
  image?: (number | null) | Media;
  currentPrice: number;
  currency: 'NGN' | 'USD' | 'GBP' | 'EUR';
  targetMarket: string;
  targetLocation: string;
  status: 'draft' | 'active' | 'inactive' | 'archived';
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulations".
 */
export interface Simulation {
  id: number;
  owner: number | User;
  product: number | Product;
  title: string;
  targetAudience: string;
  targetLocation: string;
  customerCount: number;
  /**
   * Aggregate conversation count used by dashboard reporting. Editable only by analysts and administrators.
   */
  conversationCount: number;
  status: 'draft' | 'queued' | 'running' | 'paused' | 'completed' | 'failed';
  /**
   * Calculated analysis field. Editable only by analysts and administrators.
   */
  successProbability?: number | null;
  purchaseRate?: number | null;
  repeatRate?: number | null;
  revenueMinimum?: number | null;
  revenueMaximum?: number | null;
  currency: 'NGN' | 'USD' | 'GBP' | 'EUR';
  startedAt?: string | null;
  completedAt?: string | null;
  configuration?: {
    simulationGoal?: string | null;
    marketConditions?: string | null;
    pricingStrategy?: string | null;
    customerSegments?:
      | {
          segment: string;
          id?: string | null;
        }[]
      | null;
    competitorContext?: string | null;
    additionalInstructions?: string | null;
  };
  failureReason?: string | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-agents".
 */
export interface CustomerAgent {
  id: number;
  simulation: number | Simulation;
  name: string;
  age: number;
  location: string;
  occupation?: string | null;
  incomeLevel?: string | null;
  personality?: string | null;
  interests?:
    | {
        interest: string;
        id?: string | null;
      }[]
    | null;
  buyingBehaviour?: string | null;
  priceSensitivity: 'low' | 'moderate' | 'high' | 'very-high';
  communicationStyle?: string | null;
  avatar?: (number | null) | Media;
  isActive?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  simulation: number | Simulation;
  customerAgent: number | CustomerAgent;
  status: 'pending' | 'active' | 'completed' | 'cancelled' | 'failed';
  startedAt?: string | null;
  endedAt?: string | null;
  summary?: string | null;
  messageCount?: number | null;
  lastMessageAt?: string | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  conversation: number | Conversation;
  simulation: number | Simulation;
  customerAgent?: (number | null) | CustomerAgent;
  senderType: 'customer' | 'business' | 'system';
  content: string;
  clientSubmissionId?: string | null;
  sentiment?: ('positive' | 'neutral' | 'negative' | 'mixed' | 'unknown') | null;
  buyingIntent?: ('none' | 'low' | 'medium' | 'high' | 'converted') | null;
  objectionCategory?: string | null;
  /**
   * Internal structured analysis metadata.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sentAt: string;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  simulation: number | Simulation;
  status: 'draft' | 'generating' | 'completed' | 'failed';
  successProbability: number;
  positiveSentiment: number;
  neutralSentiment: number;
  negativeSentiment: number;
  positiveFeedback?:
    | {
        label: string;
        description?: string | null;
        importance: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  customerObjections?:
    | {
        label: string;
        description?: string | null;
        importance: 'low' | 'medium' | 'high' | 'critical';
        id?: string | null;
      }[]
    | null;
  optimalPriceMinimum: number;
  optimalPriceMaximum: number;
  currentAveragePrice: number;
  currency: 'NGN' | 'USD' | 'GBP' | 'EUR';
  revenueMinimum: number;
  revenueMaximum: number;
  riskFactors?:
    | {
        label: string;
        description?: string | null;
        importance: 'low' | 'medium' | 'high' | 'critical';
        id?: string | null;
      }[]
    | null;
  recommendations?:
    | {
        label: string;
        description?: string | null;
        importance: 'low' | 'medium' | 'high';
        id?: string | null;
      }[]
    | null;
  executiveSummary: string;
  generatedAt?: string | null;
  version: number;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-simulation-requests".
 */
export interface CustomSimulationRequest {
  id: number;
  customerName: string;
  email: string;
  company: string;
  businessType: string;
  productName: string;
  productDescription: string;
  targetMarket: string;
  targetLocation: string;
  targetCustomers: string;
  currentPrice?: number | null;
  currency: 'NGN' | 'USD' | 'GBP' | 'EUR';
  businessChallenge: string;
  simulationGoal: string;
  budget?: number | null;
  timeline: string;
  /**
   * Structured summary of the deterministic request flow. Not AI generated.
   */
  conversationSummary?: string | null;
  status: 'new' | 'reviewing' | 'approved' | 'rejected' | 'converted';
  submittedAt?: string | null;
  convertedProduct?: (number | null) | Product;
  convertedSimulation?: (number | null) | Simulation;
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'simulations';
        value: number | Simulation;
      } | null)
    | ({
        relationTo: 'customer-agents';
        value: number | CustomerAgent;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'custom-simulation-requests';
        value: number | CustomSimulationRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  avatar?: T;
  isActive?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  metaTitle?: T;
  metaDescription?: T;
  hero?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
      };
  contentBlocks?:
    | T
    | {
        content?: T | ContentBlockSelect<T>;
        'feature-grid'?: T | FeatureGridBlockSelect<T>;
      };
  publishedAt?: T;
  author?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  image?: T;
  primaryAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeatureGridBlock_select".
 */
export interface FeatureGridBlockSelect<T extends boolean = true> {
  heading?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  owner?: T;
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  image?: T;
  currentPrice?: T;
  currency?: T;
  targetMarket?: T;
  targetLocation?: T;
  status?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulations_select".
 */
export interface SimulationsSelect<T extends boolean = true> {
  owner?: T;
  product?: T;
  title?: T;
  targetAudience?: T;
  targetLocation?: T;
  customerCount?: T;
  conversationCount?: T;
  status?: T;
  successProbability?: T;
  purchaseRate?: T;
  repeatRate?: T;
  revenueMinimum?: T;
  revenueMaximum?: T;
  currency?: T;
  startedAt?: T;
  completedAt?: T;
  configuration?:
    | T
    | {
        simulationGoal?: T;
        marketConditions?: T;
        pricingStrategy?: T;
        customerSegments?:
          | T
          | {
              segment?: T;
              id?: T;
            };
        competitorContext?: T;
        additionalInstructions?: T;
      };
  failureReason?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-agents_select".
 */
export interface CustomerAgentsSelect<T extends boolean = true> {
  simulation?: T;
  name?: T;
  age?: T;
  location?: T;
  occupation?: T;
  incomeLevel?: T;
  personality?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  buyingBehaviour?: T;
  priceSensitivity?: T;
  communicationStyle?: T;
  avatar?: T;
  isActive?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  simulation?: T;
  customerAgent?: T;
  status?: T;
  startedAt?: T;
  endedAt?: T;
  summary?: T;
  messageCount?: T;
  lastMessageAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  simulation?: T;
  customerAgent?: T;
  senderType?: T;
  content?: T;
  clientSubmissionId?: T;
  sentiment?: T;
  buyingIntent?: T;
  objectionCategory?: T;
  metadata?: T;
  sentAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  simulation?: T;
  status?: T;
  successProbability?: T;
  positiveSentiment?: T;
  neutralSentiment?: T;
  negativeSentiment?: T;
  positiveFeedback?:
    | T
    | {
        label?: T;
        description?: T;
        importance?: T;
        id?: T;
      };
  customerObjections?:
    | T
    | {
        label?: T;
        description?: T;
        importance?: T;
        id?: T;
      };
  optimalPriceMinimum?: T;
  optimalPriceMaximum?: T;
  currentAveragePrice?: T;
  currency?: T;
  revenueMinimum?: T;
  revenueMaximum?: T;
  riskFactors?:
    | T
    | {
        label?: T;
        description?: T;
        importance?: T;
        id?: T;
      };
  recommendations?:
    | T
    | {
        label?: T;
        description?: T;
        importance?: T;
        id?: T;
      };
  executiveSummary?: T;
  generatedAt?: T;
  version?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-simulation-requests_select".
 */
export interface CustomSimulationRequestsSelect<T extends boolean = true> {
  customerName?: T;
  email?: T;
  company?: T;
  businessType?: T;
  productName?: T;
  productDescription?: T;
  targetMarket?: T;
  targetLocation?: T;
  targetCustomers?: T;
  currentPrice?: T;
  currency?: T;
  businessChallenge?: T;
  simulationGoal?: T;
  budget?: T;
  timeline?: T;
  conversationSummary?: T;
  status?: T;
  submittedAt?: T;
  convertedProduct?: T;
  convertedSimulation?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}