const path = require('node:path');

const swaggerJsdoc = require('swagger-jsdoc');

// Resolved relative to *this file's own location* so the glob below finds
// route annotations regardless of the process's current working directory.
const routesDirectory = path.join(__dirname, '../routes');

const openApiDocument = swaggerJsdoc({
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'Parallel Market AI API',
      version: '0.1.0',
      description: 'Express + MongoDB backend. Authentication, user profile management, Products, Customers, Simulations, Customer Agents, Reports, Insights, Conversations, and Messages are implemented; every other resource is a placeholder.',
    },
    servers: [{ url: '/api', description: 'API root' }],
    tags: [
      { name: 'Health' },
      { name: 'Auth' },
      { name: 'Users' },
      { name: 'Products' },
      { name: 'Customers' },
      { name: 'Simulations' },
      { name: 'Customer Agents' },
      { name: 'Conversations' },
      { name: 'Messages' },
      { name: 'Reports' },
      { name: 'Insights' },
      { name: 'Request Simulation' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6512f9f1a1b2c3d4e5f60789' },
            fullName: { type: 'string', example: 'Daniel Adeyemi' },
            email: { type: 'string', format: 'email', example: 'demo-owner@parallel-market-ai.local' },
            role: { type: 'string', enum: ['ADMIN', 'BUSINESS_OWNER', 'ANALYST', 'VIEWER'], example: 'BUSINESS_OWNER' },
            avatar: { type: 'string', nullable: true, example: null },
            companyName: { type: 'string', nullable: true, example: 'Parallel Market Demo Ventures' },
            phone: { type: 'string', nullable: true, example: null },
            isActive: { type: 'boolean', example: true },
            emailVerified: { type: 'boolean', example: false },
            lastLogin: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        AuthTokens: {
          type: 'object',
          properties: {
            user: { $ref: '#/components/schemas/User' },
            accessToken: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
            refreshToken: { type: 'string', example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...' },
          },
        },
        OwnerSummary: {
          type: 'object',
          description: 'A trimmed, non-sensitive view of the User who owns this resource.',
          properties: {
            id: { type: 'string', example: '6512f9f1a1b2c3d4e5f60789' },
            fullName: { type: 'string', example: 'Daniel Adeyemi' },
            email: { type: 'string', format: 'email', example: 'demo-owner@parallel-market-ai.local' },
            companyName: { type: 'string', nullable: true, example: 'Parallel Market Demo Ventures' },
          },
        },
        Product: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6602a1f1a1b2c3d4e5f60abc' },
            name: { type: 'string', example: 'Starter Market Simulation Pack' },
            description: { type: 'string', example: 'A bundle of pre-configured simulations for early-stage founders.' },
            category: { type: 'string', nullable: true, example: 'Simulations' },
            price: { type: 'number', example: 49.99 },
            currency: { type: 'string', example: 'USD' },
            status: { type: 'string', enum: ['draft', 'active', 'archived'], example: 'active' },
            targetAudience: { type: 'string', nullable: true, example: 'Early-stage B2B SaaS founders' },
            features: { type: 'array', items: { type: 'string' }, example: ['Custom personas', 'Weekly reports'] },
            imageUrl: { type: 'string', nullable: true, example: 'https://cdn.example.com/products/starter-pack.png' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        Customer: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6602a1f1a1b2c3d4e5f60def' },
            fullName: { type: 'string', example: 'Amara Okafor' },
            email: { type: 'string', format: 'email', example: 'amara@brightretail.com' },
            phone: { type: 'string', nullable: true, example: '+2348012345678' },
            company: { type: 'string', nullable: true, example: 'Bright Retail Co.' },
            industry: { type: 'string', nullable: true, example: 'Retail' },
            jobTitle: { type: 'string', nullable: true, example: 'Head of Operations' },
            country: { type: 'string', nullable: true, example: 'Nigeria' },
            tags: { type: 'array', items: { type: 'string' }, example: ['vip', 'early-adopter'] },
            notes: { type: 'string', nullable: true, example: 'Interested in the enterprise tier.' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            status: { type: 'string', enum: ['active', 'inactive'], example: 'active' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ProductSummary: {
          type: 'object',
          description: 'A trimmed view of the Product this simulation is built on.',
          properties: {
            id: { type: 'string', example: '6602a1f1a1b2c3d4e5f60abc' },
            name: { type: 'string', example: 'Starter Market Simulation Pack' },
            category: { type: 'string', nullable: true, example: 'Simulations' },
            price: { type: 'number', example: 49.99 },
            currency: { type: 'string', example: 'USD' },
          },
        },
        SimulationSummary: {
          type: 'object',
          description: 'A trimmed view of the Simulation this customer agent belongs to.',
          properties: {
            id: { type: 'string', example: '6702a1f1a1b2c3d4e5f60aaa' },
            title: { type: 'string', example: 'Q1 Growth Cohort Beta' },
            status: { type: 'string', enum: ['draft', 'running', 'paused', 'completed', 'cancelled'], example: 'running' },
          },
        },
        SimulationConfiguration: {
          type: 'object',
          properties: {
            language: { type: 'string', example: 'en' },
            difficulty: { type: 'string', enum: ['easy', 'medium', 'hard'], example: 'medium' },
            sentiment: { type: 'string', enum: ['positive', 'neutral', 'negative', 'mixed'], example: 'neutral' },
            customerBehavior: { type: 'string', nullable: true, example: 'Price-sensitive, compares alternatives' },
            temperature: { type: 'number', minimum: 0, maximum: 1, example: 0.7 },
            conversationLength: { type: 'integer', minimum: 1, example: 10 },
            allowInterruptions: { type: 'boolean', example: true },
          },
        },
        SimulationStatistics: {
          type: 'object',
          description: 'Automatically calculated — never accepted from client input. See ARCHITECTURE.md for the deterministic formulas.',
          properties: {
            conversationCount: { type: 'integer', example: 8 },
            completionRate: { type: 'number', example: 45 },
            averageSentiment: { type: 'number', example: 50 },
            responseRate: { type: 'number', example: 80 },
          },
        },
        Simulation: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6702a1f1a1b2c3d4e5f60aaa' },
            title: { type: 'string', example: 'Q1 Growth Cohort Beta' },
            description: { type: 'string', example: 'Simulating price-sensitive SMB buyers evaluating the Starter Pack.' },
            industry: { type: 'string', nullable: true, example: 'Retail' },
            targetAudience: { type: 'string', nullable: true, example: 'SMB operations leads' },
            objective: { type: 'string', nullable: true, example: 'Validate pricing sensitivity before GA launch' },
            customerCount: { type: 'integer', example: 10 },
            status: { type: 'string', enum: ['draft', 'running', 'paused', 'completed', 'cancelled'], example: 'draft' },
            progress: { type: 'integer', minimum: 0, maximum: 100, example: 0 },
            startedAt: { type: 'string', format: 'date-time', nullable: true },
            completedAt: { type: 'string', format: 'date-time', nullable: true },
            estimatedDuration: { type: 'integer', nullable: true, example: 30 },
            configuration: { $ref: '#/components/schemas/SimulationConfiguration' },
            statistics: { $ref: '#/components/schemas/SimulationStatistics' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            product: { $ref: '#/components/schemas/ProductSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CustomerAgentMetadata: {
          type: 'object',
          properties: {
            tags: { type: 'array', items: { type: 'string' }, example: ['skeptical', 'budget-conscious'] },
            score: { type: 'integer', minimum: 0, maximum: 100, example: 70 },
            notes: { type: 'string', nullable: true, example: 'Responds well to ROI-focused framing.' },
          },
        },
        CustomerAgent: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6702a1f1a1b2c3d4e5f60bbb' },
            name: { type: 'string', example: 'Sarah Chen' },
            avatar: { type: 'string', nullable: true, example: 'https://cdn.example.com/agents/sarah-chen.png' },
            age: { type: 'integer', nullable: true, example: 34 },
            occupation: { type: 'string', nullable: true, example: 'Operations Manager' },
            location: { type: 'string', nullable: true, example: 'Austin, TX' },
            income: { type: 'string', nullable: true, example: '$60,000–$80,000' },
            personality: { type: 'string', nullable: true, example: 'Analytical, cautious, detail-oriented' },
            goals: { type: 'array', items: { type: 'string' }, example: ['Reduce operational costs', 'Improve team efficiency'] },
            painPoints: { type: 'array', items: { type: 'string' }, example: ['Limited budget', 'Slow approval process'] },
            buyingBehavior: { type: 'string', nullable: true, example: 'Compares at least three vendors before deciding' },
            communicationStyle: { type: 'string', nullable: true, example: 'Direct, prefers data over narrative' },
            sentiment: { type: 'string', enum: ['positive', 'neutral', 'negative', 'mixed'], example: 'neutral' },
            status: { type: 'string', enum: ['active', 'inactive'], example: 'active' },
            metadata: { $ref: '#/components/schemas/CustomerAgentMetadata' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            simulation: { $ref: '#/components/schemas/SimulationSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ReportMetrics: {
          type: 'object',
          description: 'Automatically calculated from the source simulation — never accepted from client input. See ARCHITECTURE.md for the deterministic formulas.',
          properties: {
            conversationCount: { type: 'integer', example: 8 },
            completionRate: { type: 'number', example: 100 },
            responseRate: { type: 'number', example: 80 },
            averageSentiment: { type: 'number', example: 75 },
            positiveResponses: { type: 'integer', example: 5 },
            neutralResponses: { type: 'integer', example: 2 },
            negativeResponses: { type: 'integer', example: 1 },
            averageResponseTime: { type: 'number', example: 45, description: 'Seconds.' },
            conversionScore: { type: 'number', example: 92 },
            engagementScore: { type: 'number', example: 77.5 },
          },
        },
        ReportRecommendation: {
          type: 'object',
          description: 'Server-generated from `metrics` via fixed threshold rules — never accepted from client input.',
          properties: {
            title: { type: 'string', example: 'Scale Successful Approach' },
            description: { type: 'string', example: 'Conversion score is 92/100 with more positive than negative responses.' },
            priority: { type: 'string', enum: ['Low', 'Medium', 'High'], example: 'Low' },
          },
        },
        Report: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6802a1f1a1b2c3d4e5f60ccc' },
            title: { type: 'string', example: 'Q1 Growth Cohort Beta — Report' },
            description: { type: 'string', nullable: true },
            summary: { type: 'string', example: '"Q1 Growth Cohort Beta" completed 8 conversation(s) with a 100% completion rate and a 80% response rate. Conversion score: 92/100. Engagement score: 77/100.' },
            metrics: { $ref: '#/components/schemas/ReportMetrics' },
            recommendations: { type: 'array', items: { $ref: '#/components/schemas/ReportRecommendation' } },
            status: { type: 'string', enum: ['Draft', 'Generated', 'Archived'], example: 'Generated' },
            generatedAt: { type: 'string', format: 'date-time' },
            generatedBy: { $ref: '#/components/schemas/OwnerSummary' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            simulation: { $ref: '#/components/schemas/SimulationSummary' },
            product: { $ref: '#/components/schemas/ProductSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ReportSummary: {
          type: 'object',
          description: 'A trimmed view of the Report this insight belongs to.',
          properties: {
            id: { type: 'string', example: '6802a1f1a1b2c3d4e5f60ccc' },
            title: { type: 'string', example: 'Q1 Growth Cohort Beta — Report' },
            status: { type: 'string', enum: ['Draft', 'Generated', 'Archived'], example: 'Generated' },
          },
        },
        InsightMetadata: {
          type: 'object',
          properties: {
            tags: { type: 'array', items: { type: 'string' }, example: ['conversion'] },
            source: { type: 'string', example: 'deterministic-engine' },
            notes: { type: 'string', nullable: true },
          },
        },
        Insight: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6802a1f1a1b2c3d4e5f60ddd' },
            title: { type: 'string', example: 'Strong Conversion' },
            category: { type: 'string', example: 'conversion' },
            description: { type: 'string', example: 'Conversion score of 92/100 reflects strong completion and response rates together.' },
            importance: { type: 'string', enum: ['Low', 'Medium', 'High', 'Critical'], example: 'Medium' },
            trend: { type: 'string', enum: ['Positive', 'Neutral', 'Negative'], example: 'Positive' },
            score: { type: 'number', example: 92 },
            metadata: { $ref: '#/components/schemas/InsightMetadata' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            report: { $ref: '#/components/schemas/ReportSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        CustomerAgentSummary: {
          type: 'object',
          description: 'A trimmed view of the Customer Agent this conversation belongs to.',
          properties: {
            id: { type: 'string', example: '6702a1f1a1b2c3d4e5f60bbb' },
            name: { type: 'string', example: 'Sarah Chen' },
            status: { type: 'string', enum: ['active', 'inactive'], example: 'active' },
          },
        },
        ConversationMetadata: {
          type: 'object',
          properties: {
            tags: { type: 'array', items: { type: 'string' }, example: ['pricing'] },
            source: { type: 'string', nullable: true, example: 'simulation-runner' },
            notes: { type: 'string', nullable: true },
          },
        },
        Conversation: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6902a1f1a1b2c3d4e5f60eee' },
            title: { type: 'string', example: 'Pricing objections walkthrough' },
            status: { type: 'string', enum: ['Open', 'Closed', 'Archived'], example: 'Open' },
            lastMessage: { type: 'string', nullable: true, example: 'That makes sense, thanks for clarifying.' },
            lastActivity: { type: 'string', format: 'date-time', nullable: true },
            messageCount: { type: 'integer', example: 4 },
            metadata: { $ref: '#/components/schemas/ConversationMetadata' },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            simulation: { $ref: '#/components/schemas/SimulationSummary' },
            customerAgent: { $ref: '#/components/schemas/CustomerAgentSummary' },
            isActive: { type: 'boolean', example: true },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        ConversationSummary: {
          type: 'object',
          description: 'A trimmed view of the Conversation this message belongs to.',
          properties: {
            id: { type: 'string', example: '6902a1f1a1b2c3d4e5f60eee' },
            title: { type: 'string', example: 'Pricing objections walkthrough' },
            status: { type: 'string', enum: ['Open', 'Closed', 'Archived'], example: 'Open' },
          },
        },
        MessageAttachment: {
          type: 'object',
          description: 'Metadata only — no file upload is implemented in this phase.',
          properties: {
            name: { type: 'string', example: 'pricing-sheet.pdf' },
            url: { type: 'string', example: 'https://cdn.example.com/attachments/pricing-sheet.pdf' },
            mimeType: { type: 'string', nullable: true, example: 'application/pdf' },
            size: { type: 'integer', nullable: true, example: 204800 },
          },
        },
        Message: {
          type: 'object',
          properties: {
            id: { type: 'string', example: '6902a1f1a1b2c3d4e5f60fff' },
            sender: { type: 'string', nullable: true, description: 'Raw id of the User or CustomerAgent who sent this message; null for senderType "System".' },
            senderType: { type: 'string', enum: ['User', 'CustomerAgent', 'System'], example: 'User' },
            content: { type: 'string', example: 'Can you walk me through the pricing tiers again?' },
            type: { type: 'string', enum: ['Text', 'System', 'Event', 'Notification'], example: 'Text' },
            attachments: { type: 'array', items: { $ref: '#/components/schemas/MessageAttachment' } },
            metadata: { $ref: '#/components/schemas/ConversationMetadata' },
            status: { type: 'string', enum: ['Sent', 'Delivered', 'Read'], example: 'Sent' },
            isRead: { type: 'boolean', example: false },
            readAt: { type: 'string', format: 'date-time', nullable: true },
            edited: { type: 'boolean', example: false },
            editedAt: { type: 'string', format: 'date-time', nullable: true },
            deleted: { type: 'boolean', example: false },
            deletedAt: { type: 'string', format: 'date-time', nullable: true },
            owner: { $ref: '#/components/schemas/OwnerSummary' },
            conversation: { $ref: '#/components/schemas/ConversationSummary' },
            createdAt: { type: 'string', format: 'date-time' },
            updatedAt: { type: 'string', format: 'date-time' },
          },
        },
        PaginationMeta: {
          type: 'object',
          properties: {
            page: { type: 'integer', example: 1 },
            limit: { type: 'integer', example: 20 },
            totalItems: { type: 'integer', example: 42 },
            totalPages: { type: 'integer', example: 3 },
          },
        },
        ApiErrorResponse: {
          type: 'object',
          properties: {
            success: { type: 'boolean', example: false },
            message: { type: 'string' },
            data: { type: 'object', nullable: true, example: null },
            errors: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  code: { type: 'string' },
                  message: { type: 'string' },
                  field: { type: 'string' },
                },
              },
            },
            meta: {
              type: 'object',
              properties: { timestamp: { type: 'string', format: 'date-time' } },
            },
          },
        },
      },
    },
  },
  apis: [`${routesDirectory}/*.js`],
});

module.exports = { openApiDocument };
